// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVvwg-osw5Ah1wbserrLYjzVVwgSoNkzk',
    appId: '1:794341151336:web:388be9ebecb19c6d6b21dd',
    messagingSenderId: '794341151336',
    projectId: 'lapor-book-81576',
    authDomain: 'lapor-book-81576.firebaseapp.com',
    storageBucket: 'lapor-book-81576.appspot.com',
    measurementId: 'G-YZNN8GV8BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU5kn90vrEGoYpGo8uNJlXIOcrX5AZifY',
    appId: '1:794341151336:android:447bb4dc204ba2276b21dd',
    messagingSenderId: '794341151336',
    projectId: 'lapor-book-81576',
    storageBucket: 'lapor-book-81576.appspot.com',
  );
}
